apiVersion: v1
kind: Service
metadata:
  name: hospital-api
  namespace: hospital

spec:
  selector:
    app: hospital-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP